### ISSUE TITLE
Improve donate form UX

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/Website#103]
![screenshot at 2018-02-27 10 18 27](https://user-images.githubusercontent.com/6025893/36723335-dc9bff12-1ba7-11e8-8afb-9fa05c71ac33.png)

If you click 'next', the next stage doesn't confirm the amount - it just asks for  bank details

Also, I turn HTML 5 form validation off, I can try and donate an amount that isn't a number and it will just ask for my bank details. No idea what happens next..

**Comment by andylolz** [comment]
Which browser is this? I don’t see the pink background in chrome or firefox on OSX.

A radio for “Other amount” (and some javascript) would help fix some of this.

**Comment by chris48s** [comment]
> I don’t see the pink background in chrome or firefox on OSX

Probably due to #53 rather than browsers

**Comment by andylolz** [comment]
> Probably due to #53 rather than browsers

Okay so that bit of the screenshot is sorted, then?

**Comment by chris48s** [comment]
Oh, no sorry. If you hard refresh to force a reload of the CSS that bit should break for you as well.

**Comment by andylolz** [comment]
> Oh, no sorry. If you hard refresh to force a reload of the CSS that bit should break for you as well.

I tried that, and couldn’t get it to break – so I guessed you meant the other thing.

**Comment by JoeMitchell** [comment]
Some other thoughts (apologies if these should be in a difference issue)

- It's not clear to me that I have to click the small blue `Next` button — at first glance I assume that's something to do with 'Other amount'. Perhaps the amounts should themselves be buttons? (A la [Oxfam](https://www.oxfam.org.uk/donate/donate-to-oxfam) and Greenpeace). Or could that button be at least the size of the £amount grey boxes, and say `Donate`?
![image](https://user-images.githubusercontent.com/8096305/50216691-606c8c80-037e-11e9-91c7-f8920ec413bd.png)

- At wider aspects, the boxes are all different sizes. Can we force it to look like it does when narrower?
![image](https://user-images.githubusercontent.com/8096305/50216494-d45a6500-037d-11e9-971f-faf034421f5f.png)
Versus below, which is better, methinks:
![image](https://user-images.githubusercontent.com/8096305/50216507-dae8dc80-037d-11e9-8ff3-ab89d6c96ac8.png)


I like both [Oxfam](https://www.oxfam.org.uk/donate/donate-to-oxfam) and [Greenpeace's](https://secure.greenpeace.org.uk/page/contribute/greenpeace-main) efforts, in case we can just borrow them.

**Comment by pmk01** [comment]
Closing this as the donation form is very different now
