### ISSUE TITLE
Link to Slack is borken

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/Website#127]
https://slack.democracyclub.org.uk/

![image](https://user-images.githubusercontent.com/8096305/47989315-8f83b300-e0dc-11e8-842c-39a764a902b6.png)

**Comment by symroe** [comment]
The error here is:

`Bad Slack response. Make sure the team name and API keys are correct`

Might need to reset the API key.

**Comment by symroe** [comment]
@chris48s broke this. Then we fixed it again.

🎉
