### ISSUE TITLE
Change text on Paypal donate form

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/Website#131]
I assume 'Purpose' is something we have to write some words for, so we should probably write something better than 'website'. 

Purpose: to support everyone's participation in democratic life.

(Probably come back here once we've signed off our vision statement)

![screenshot 2018-12-10 at 10 03 27](https://user-images.githubusercontent.com/8096305/49725529-cb71e100-fc63-11e8-93cc-87fe1e3344d7.png)

**Comment by pmk01** [comment]
Donate form has been completely re-done, so this is obsolete.
