### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/Website#18]
One step to addressing our current issue with gender diversity would be to be explicit that it isn’t by design. That is: publicly demonstrate willingness to address this problem. A code of conduct might help do that.

I took a look at http://contributor-covenant.org/, but it seems quite focused on code contributions, rather than more general stuff (e.g. IRL / other contributions.) I wonder if there’s a similar code of conduct that better fits our needs.

**Comment by andylolz** [comment]
In b026f0bf, the listed team became exclusively “male, pale and stale” (okay, stale is maybe a bit strong).

I’d suggest either listing more core members (which would at least show some gender diversity) or listing none at all.

**Comment by JoeMitchell** [comment]
We could invite top contributors to send in a picture and a little
description of who they are and why they help?

**Comment by andylolz** [comment]
Sounds like a good plan. If they have github accounts (and most do seem to) then they can edit https://github.com/DemocracyClub/Website/blob/master/democracy_club/templates/about.html directly and send a PR (can do it all from within a browser).
