### ISSUE TITLE
Report 2016 => 500 error

### ISSUE THREAD

**Issue by VirginiaDooley** [DemocracyClub/Website#388]
### Issue and Steps to Reproduce
https://democracyclub.org.uk/report_2016/ throws a 500 error but renders fine locally. 

In researching this bug, we considered that while Sentry is set up, we aren't sure where `SENTRY_DSN` is defined in the deploy script or where this app exists in AWS. 

Furthermore, it would be useful to set up a test to catch these broken tags locally and render broken tags on staging/prod rather than 500 errors. Since static tags are used across several DC products, adding this to `dc_utils` might make the most sense. 

From @symroe We might want to do something like:
assert "pipeline.finders.PipelineFinder" in settings.STATICFILES_FINDERS, or whatever
(same for the other filders https://github.com/DemocracyClub/dc_django_utils/blob/main/dc_utils/settings/pipeline.py#L7)
dc_utils/settings/pipeline.py:7
`STATICFILES_FINDERS = (`

**Comment by VirginiaDooley** [comment]
This is no longer an issue; broken html addressed in https://github.com/DemocracyClub/Website/pull/387

**Comment by pmk01** [comment]
https://democracyclub.org.uk/report_2016/
Looks broken again, to me at least...

![Screenshot 2021-09-08 164552](https://user-images.githubusercontent.com/61510609/132541787-76641ae5-b9ed-4028-ae3f-dad7d0086d5c.png)


Relatedly, the various images across all the other reports appear to be gone, too.
