### ISSUE TITLE
Blog Heroes are big

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/Website#393]
Blog images, especially heroes, are now displaying at a much larger size, eg: https://democracyclub.org.uk/blog/2020/07/21/we-need-single-agency-be-responsible-uk-elections/

Previously they were compressed into a neat header. Compare the above with this one, which I cropped to be a header: https://democracyclub.org.uk/blog/2021/02/02/most-complex-elections-ever/

**Comment by VirginiaDooley** [comment]
@pmk01 is this still an issue for (new) blog posts?

**Comment by pmk01** [comment]
I think you're right; It's possible we just need to be more careful with the images we use... closing this anyway
