### ISSUE TITLE
Image preview broken on website

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/Website#394]
Previously the image preview ('metaimage'?) showed blog heroes when shared. Now we get a big Democratick instead:

![blog](https://user-images.githubusercontent.com/61510609/127630629-34564e16-03cc-4578-82cc-83124e89d533.png)

**Comment by pmk01** [comment]
This appears to be fixed on Twitter, but still affects Facebook 

![Screenshot 2021-09-16 114722](https://user-images.githubusercontent.com/61510609/133599141-5067eee6-cd65-4b12-a60d-ad8cadb50e49.png)

**Comment by VirginiaDooley** [comment]
I found this on YNR and thought something similar this might help: 
` def get_display_image_url(self):
        """
        Return either the person's primary image or blank outline of a person
        """
        if self.primary_image:
            try:
                return get_thumbnail(self.primary_image.file, "x64").url
            except FileNotFoundError:
                pass

        return static("candidates/img/blank-person.png")
`
`<meta property="og:image" content="{{ person.get_display_image_url }}" />`

**Comment by VirginiaDooley** [comment]
> On the same theme, WCIVF still just gives us a big 'Can'.
> 
> ![Can](https://user-images.githubusercontent.com/61510609/138247929-66c296ba-1f16-4726-bdcb-ecf4f5a3c13a.png)

Twitter previews for WCIVF show the "tick" logo.

**Comment by VirginiaDooley** [comment]
Completed with #563

**Comment by symroe** [comment]
Working on Mastodon: 
![image](https://user-images.githubusercontent.com/242329/203546596-f01133a9-3f1c-4cee-8e25-abd12840ae39.png)
