### ISSUE TITLE
Nicer blog subtitles

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/Website#45]
At the moment, the blog automatically adds a data/time/author line to every post. Like this: 

![image](https://cloud.githubusercontent.com/assets/8096305/19599933/acf247b8-979a-11e6-90ed-1226082e0020.png)

I think it would look nicer like this: 

[Blog title]
Friday, 21 October 2016
Joe Mitchell

[body]

**Comment by JoeMitchell** [comment]
There's also something weird happening where it doesn't leave any space under the auto-generated line. So a line <br> or so in there would be lovely...

**Comment by symroe** [comment]
Fixed?

**Comment by JoeMitchell** [comment]
Nearly! But...

![ordnance_survey_are_getting_in_the_way_of_open_election_data___democracy_clubdemocracy_club](https://cloud.githubusercontent.com/assets/8096305/23514479/5b009da6-ff5f-11e6-880f-f1000072eaec.jpg)

**Comment by symroe** [comment]
I think a newline looked a bit silly:

![screenshot 2017-03-08 17 15 13](https://cloud.githubusercontent.com/assets/242329/23714935/ee6920f0-0422-11e7-9a05-273cc2bd8dc6.png)


So I just added more space:

![screenshot 2017-03-08 17 15 25](https://cloud.githubusercontent.com/assets/242329/23714938/f44c3db8-0422-11e7-82d5-b1d24f657e48.png)

How's that?

**Comment by JoeMitchell** [comment]
Yeah, done!
