### ISSUE TITLE
Hide inactive users from the blog post author dropdown

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/Website#535]
Currently when adding a blog post, there is a list of all users to pick from.

This includes all users, even those marked as "inactive" in the Django admin.

We should filter this list to only include "active" users. This allows us to, for example, remove people from the list who have written blog posts in the past but who no longer work for DC.

**Comment by VirginiaDooley** [comment]
Waiting on https://github.com/DemocracyClub/Website/pull/545
