### ISSUE TITLE
Blog post admin interface improvements

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/Website#536]
* Filters for: published, author(s), tags
* Search for titles
* Author in list_display

**Comment by pmk01** [comment]
As a note on this, various links on our site lead to URLs which imply filters, but do not actually filter, eg.: https://democracyclub.org.uk/blog/?tag=research

**Comment by VirginiaDooley** [comment]
> As a note on this, various links on our site lead to URLs which imply filters, but do not actually filter, eg.: https://democracyclub.org.uk/blog/?tag=research

It seems the issue with the filter is that it only works if the post has a single tag, but it will not work if `post.tags = ['blog', 'research']`

**Comment by VirginiaDooley** [comment]
> As a note on this, various links on our site lead to URLs which imply filters, but do not actually filter, eg.: https://democracyclub.org.uk/blog/?tag=research

I've looked further into this and it does work locally, but definitely not in production.

**Comment by VirginiaDooley** [comment]
`Author in list_display` will not be possible because the value of`list_display` must not be a ManyToManyField.
