### ISSUE TITLE
Why is this <input> so small compared to the text around it ? 

### ISSUE THREAD

**Issue by davidmiller** [DemocracyClub/Website#59]
![screen shot 2017-04-27 at 11 37 04](https://cloud.githubusercontent.com/assets/17229/25479768/eeab445c-2b3d-11e7-98a2-602d60ffa34e.png)

Suggest this: 

![screen shot 2017-04-27 at 11 40 10](https://cloud.githubusercontent.com/assets/17229/25479875/55cf0f7e-2b3e-11e7-9e9a-0f241e4cc3af.png)

```css
    font-size: 22px;
    margin-left: 12px;
    line-height: 18px;
    padding-top: 3px;
    padding-bottom: 3px;
    padding-left: 6px;
    margin-top: 30px;
    color: #58595b;
```

**Comment by JoeMitchell** [comment]
Haha — I have often wondered this.

**Comment by JoeMitchell** [comment]
Ooh, this might be solved now?
