### ISSUE TITLE
Add title of blog to RSS feed

### ISSUE THREAD

**Issue by agvbergin** [DemocracyClub/Website#591]
### Issue and Steps to Reproduce

Go to

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdemocracyclub.org.uk%2Fblog%2Ffeed%2F

to see the results for validating the [Democracy Club blog's RSS feed](https://democracyclub.org.uk/blog/feed/)

#### Expected

Blog feed validates.

#### Actual

Blog feed does not validate with several warnings, including empty `<title></title>` tags.

### Additional Details

The RSS feed still works fine and I can read your content (thank you!); however, as it's missing the blog title (e.g. something like "Democracy Club") it's hard to identify who the content is coming from within my feed reader (Feedly, both web app and iOS app).

**Comment by VirginiaDooley** [comment]
@agvbergin Thanks so much for bringing this issue to our attention.
