### ISSUE TITLE
Add Welsh Government/GLA to front page logos

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/Website#657]
I propose replacing The Times & Telegraph with Welsh Government and Greater London Authority logos, which are a bit more impressive partners. If we then also switch the Google and Parliament logos, that gives us a nice 'official' top row when viewed on a monitor.

**Comment by VirginiaDooley** [comment]
Can we do all? While I see your point, the inclusion of The Times & Telegraph show commercial/media potential. Will we add BBC?

**Comment by pmk01** [comment]
One problem is that too many logos take ages to scroll past on a phone!
