### ISSUE TITLE
Needs obvious homepage link to Who Can I Vote For?

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/Website#70]
Traffic from YourVoteMatters is going to democracyclub.org.uk and would probably benefit from going onto WhoCanIVoteFor.co.uk. Although ~5% of ~1% is not a lot, though a few million people on YVM is quite likely. 

_Pause on this until EC confirm that they won't link to Who instead_

**Comment by robzor** [comment]
New DC website IA refactor is live, so there is now an obvious homepage link to WCIVF :)
