### ISSUE TITLE
Alt text for blog header images

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/Website#734]
It would be nice if we could add alt text to blog headers, for screen readers.

**Comment by VirginiaDooley** [comment]
> It would be nice if we could add alt text to blog headers, for screen readers.

Good idea. Can you add this to the Website work for this sprint? It will be easy to combine in one PR.

**Comment by VirginiaDooley** [comment]
Closing as this feature request was added with https://github.com/DemocracyClub/Website/pull/755
