### ISSUE TITLE
Blog header image is blurry

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/Website#784]
When a Hero image is uploaded to a blog, it gets compressed along the way and comes out blurry. This is mainly noticeable when the image uses text: https://democracyclub.org.uk/blog/2024/02/23/dealing-with-electoral-change-and-uncertainty/

**Comment by symroe** [comment]
Two things to do here:

1. use `format="PNG"` in the `thumbnail` template tags
2. Make the width wider. It's currently `690` but the width of the site on desktop is `890`

We need to make the OG images PNG too, but they don't need to be wider, I don't think
