### ISSUE TITLE
Link to blog RSS Feed in site footer

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/Website#85]
People should be able to subscribe to our blog. It is currently kind of strange that disqus has subscribe buttons on it that subscribe you to the comments (which is not that helpful) but there is no subscribe  feature for the blog itself.
This might actually be an issue for https://github.com/DemocracyClub/django-hermes but meh..

**Comment by chris48s** [comment]
Now that https://github.com/DemocracyClub/django-hermes/pull/2 is in we can probably at least add 'subscribe via RSS' easily: https://democracyclub.org.uk/blog/feed/

**Comment by symroe** [comment]
"Blog RSS/Atom feed" is in the footer, and there's a `link rel="alternate"` tag in the HTML head, meaning services like Firefox's `live bookmarks` and feedly can auto-discover it.

You're thinking about an actual "RSS icon" style button (maybe not using the icon)?

**Comment by chris48s** [comment]
I guess the main thing I was thinking when I originally raised this issue was that if you look at one of our blog posts, the only button on the page that says "subscribe" subscribes you to the DisQus comments thread for that specific blog post which may not be the expected behaviour for someone clicking it. Also it is above the 'RSS feed' link in the footer. I did not necessarily have fully formed opinions about the merits of mailing list/RSS/etc.

This feed improvement just seemed relevant to add to the mix..

**Comment by VirginiaDooley** [comment]
The RSS feed is linked in the footer
